### ISSUE TITLE
Lucky major bug

### ISSUE THREAD

**Issue by AccioAce** [TheBusyBiscuit/luckyblocks-sf#15] opened 2020-02-16 18:45 UTC
## Description (Required)
Lucky block bug: When you place a lucky block and break it while in the creative mode it works fine. But when you try breaking the lucky block while in survival mode it turns the lucky block into cs-core lib heads.

## Steps to reproduce the Issue (Required)
I hope the description helped.

## Expected behavior (Required)
I excepted while being in survival mode, players would be able to place their luckyblock down and break it, I don't except luckyblock to turn into core-lib heads.

## Environment (Required)

https://gyazo.com/a5f6ef1d0e95917a8233645d30723bf5 https://gyazo.com/a5f6ef1d0e95917a8233645d30723bf5
Minecraft Version: 1.15.2
Slimefun Version: Slimefun4 - #443
CS-CoreLib Version: CS-CoreLib - #83
Luckyblock Version: luckyblocks-sf - #18

**Comment by TheBusyBiscuit** [comment] 2020-02-16 18:46
Duplicate of #14

**Closed** 2020-02-16 18:45 UTC
Labels: bug
